---
# tasks file for redhat-7

- name: Lets' update the scap content first make sure you can pull updates.
  yum:
   name: scap-security-guide
   state: latest

- name: detectiing which systems are using a graphical or command line interface.
  command: "systemctl get-default"
  register: default

- name: scanning systems with a graphical interface , skipping those without
  command: oscap xccdf eval --profile "{{gui}}" --report "{{html}}" --stig-view "{{view}}" "{{rhel7}}"
  when: default.stdout == "graphical.target"
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: scanning systems with a command interface , skipping those without
  command: oscap xccdf eval --profile "{{cli}}" --report "{{html}}" --stig-view "{{view}}" "{{rhel7}}"
  when: default.stdout == "multi-user.target"
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: downloading reports to ../oscap-reports directory
  fetch:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    flat: yes
  with_items:
    - {src: "{{html}}", dest: "../oscap-reports/{{inventory_hostname}}.html" }     
    - {src: "{{view}}", dest: "../oscap-reports/{{inventory_hostname}}.xml" }     
